/**
 * Parses a scanned QR code string and extracts the asset tag ID.
 *
 * Supports two formats:
 *  1. JSON payload (generated by this app):
 *     { type: "asset", id: "<uuid>", assetTagId: "<asset_tag_id>", url: "..." }
 *  2. Plain string containing just the asset tag ID (e.g. "PT2021-0001")
 *
 * Returns the asset tag ID string, or null if the payload cannot be parsed
 * as either an asset QR or a plain asset ID.
 */
export function parseAssetQrCode(raw: string): string | null {
    const trimmed = raw.trim()

    // ── Try JSON format first ──────────────────────────────────────────────────
    try {
        const parsed = JSON.parse(trimmed)

        if (parsed && parsed.type === "asset") {
            // Prefer assetTagId (human-readable); fall back to id field
            const tagId: string =
                parsed.assetTagId || parsed.asset_tag_id || parsed.id || ""

            return tagId.trim() || null
        }
    } catch {
        // Not JSON – fall through to plain-string handling
    }

    // ── Try URL format: https://host/assets/<id> ───────────────────────────────
    try {
        const url = new URL(trimmed)
        const pathParts = url.pathname.split("/").filter(Boolean)
        if (pathParts.length >= 2 && pathParts[pathParts.length - 2] === "assets") {
            return decodeURIComponent(pathParts[pathParts.length - 1]) || null
        }
    } catch {
        // Not a valid URL
    }

    // ── Plain asset tag ID ─────────────────────────────────────────────────────
    // Accept the raw string if it looks like an asset tag (non-empty, no JSON chars)
    if (trimmed && !trimmed.startsWith("{") && !trimmed.startsWith("[")) {
        return trimmed
    }

    return null
}
